In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Zeros array
arr0 = np.zeros(5,dtype="int")
arr0

array([0, 0, 0, 0, 0])

In [22]:

arr1 =np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 7]])

In [17]:
arr1.dtype

dtype('int64')

In [20]:
arr1.shape

(4, 3)

In [ ]:
# Swapping
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])
swapped=np.swapaxes(arr1,0,1,)
swapped

array([[1, 4, 7, 3],
       [2, 5, 8, 4],
       [3, 6, 9, 7]])

In [28]:
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])
print(arr1.max())

9


In [ ]:
# Reshape
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])

arr1.reshape(3,4)




array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 4, 7]])

In [ ]:
# linspace
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])
lin_arr = np.linspace(np.min(arr1), np.max(arr1), num=10)
print(lin_arr)


[1.         1.88888889 2.77777778 3.66666667 4.55555556 5.44444444
 6.33333333 7.22222222 8.11111111 9.        ]


In [1]:
import numpy as np

In [ ]:
# Array in matrics Form
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr1=np.array([[3,2,1],[5,4,3]])
arr1


array([[3, 2, 1],
       [5, 4, 3]])

In [ ]:
# Reshape
arr1 =np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,7]])

arr1.reshape(3,4)



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 4, 7]])

In [ ]:
# Addition of 2D Array
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(x)
print(y)
print("------------------------")
z=x+y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------------------
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
#Multiplication
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(x)
print(y)
print("------------------------")
z=x*y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------------------
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [ ]:
#division,substraction
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(x)
print(y)
print("------------------------")
z=x/y
print(z)
print("-------------------------")
z=x-y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------------------
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
-------------------------
[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


In [ ]:
# INDEXING
arr2=np.array([2,3,4,5,6,7,8])
print(arr2)
print(arr2[1])
print(arr2[-1])
print(arr2[4])

[2 3 4 5 6 7 8]
3
8
6


In [4]:
# Arrange
import numpy as np
arr2 = np.array([2,3,4,5,6,7,8])

arr3 = np.arange(2, 9)  # Generates [2, 3, 4, 5, 6, 7, 8]

arr3



array([2, 3, 4, 5, 6, 7, 8])