In [ ]:
# NAME : ADHAV SAURABH DNYANDEV
# ROLL NO : 02

# Import Library
import numpy as np
import pandas as pd



In [ ]:
 #Load CSV file
df = pd.read_csv('student_dataset.csv')  


In [4]:
# Convert columns to numpy arrays
ids = df['ID'].to_numpy()
names = df['Name'].to_numpy()
ages = df['Age'].to_numpy()
marks = df['Marks'].to_numpy()
genders = df['Gender'].to_numpy()

In [5]:
print("Shape:", df.shape)
print("Columns:", df.columns.to_list())
print()

Shape: (1000, 5)
Columns: ['ID', 'Name', 'Age', 'Marks', 'Gender']



In [6]:
# 1D array example
print("1D Age array:", ages[:10])


1D Age array: [24 21 22 24 20 22 22 24 19 20]


In [7]:
# 2D array (Age & Marks together)
age_marks = df[['Age','Marks']].to_numpy()
print("2D Age-Marks shape:", age_marks.shape)

2D Age-Marks shape: (1000, 2)


In [8]:
# Array attributes
print("ndim:", age_marks.ndim)
print("dtype:", age_marks.dtype)
print("size:", age_marks.size)
print("itemsize:", age_marks.itemsize)
print("nbytes:", age_marks.nbytes)


ndim: 2
dtype: int64
size: 2000
itemsize: 8
nbytes: 16000


In [9]:
# Get first 5 names
print("First 5 students:", names[:5])

First 5 students: ['Student_1' 'Student_2' 'Student_3' 'Student_4' 'Student_5']


In [10]:
# Get last 5 marks
print("Last 5 marks:", marks[-5:])

Last 5 marks: [82 73 96 65 80]


In [12]:
print("Average Age:", np.mean(ages))

Average Age: 20.96


In [13]:
print("Max Marks:", np.max(marks))

Max Marks: 100


In [14]:
print("Min Marks:", np.min(marks))

Min Marks: 40


In [15]:
print("Median Marks:", np.median(marks))

Median Marks: 70.0


In [16]:
print("Standard Deviation of Marks:", np.std(marks))

Standard Deviation of Marks: 17.459901947032805


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)       # [1 2 3 4]
print(type(arr)) # <class 'numpy.ndarray'>


[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
np.arange(1, 10, 2)   # [1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [19]:
np.linspace(0, 1, 5)  # [0.   0.25  0.5  0.75  1. ]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
a = np.arange(6)          # [0 1 2 3 4 5]
a = a.reshape(2, 3)        # [[0 1 2]
                           #  [3 4 5]]


In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]
print(a * b)  # [ 4 10 18]
print(a / b)  # [0.25 0.4  0.5 ]
print(a ** 2) # [1 4 9]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [22]:
arr = np.array([10, 20, 5, 30])
np.argmax(arr)   # 3
np.argmin(arr)   # 2


np.int64(2)

In [23]:
arr = np.array([2, 4, 7, 11])
np.diff(arr)    # [2 3 4]


array([2, 3, 4])